"""Paid Nano Banana path (gemini-2.5-flash-image)."""

from __future__ import annotations

import base64
import logging

from google import genai

from app.models.image import ImageGenerationRequest, ImageGenerationResponse
from app.services.providers.base import decode_optional_image
from app.utils.prompts import EDIT_PROMPT, GENERATE_PROMPT

log = logging.getLogger(__name__)


class GeminiImageProvider:
    def __init__(self) -> None:
        self.client = genai.Client()
        self.model = "gemini-2.5-flash-image"

    async def generate(
        self, request: ImageGenerationRequest
    ) -> ImageGenerationResponse:
        log.info("Using IMAGE_PROVIDER=gemini-image (paid Nano Banana)")
        prompt_template = GENERATE_PROMPT if request.type == "generate" else EDIT_PROMPT
        prompt = prompt_template.format(user_prompt=request.prompt)

        contents: list = [prompt]
        reference = decode_optional_image(request.image_data)
        if reference is not None:
            contents.append(reference)

        try:
            response = self.client.models.generate_content(
                model=self.model, contents=contents
            )
        except Exception as e:
            log.error("Error calling Gemini image API: %s", e)
            raise RuntimeError(f"Failed to generate image: {e}") from e

        if not response.candidates:
            raise ValueError("No response generated by the model")

        generated_image_data = None
        text_response = None
        for part in response.candidates[0].content.parts:
            if part.text is not None:
                text_response = part.text
            elif part.inline_data is not None:
                generated_image_data = base64.b64encode(part.inline_data.data).decode(
                    "utf-8"
                )

        if not generated_image_data:
            raise ValueError("No image generated by the model")

        return ImageGenerationResponse(
            image_data=generated_image_data, text_response=text_response
        )
