"""Nano Banana path (gemini-2.5-flash-image)."""

from __future__ import annotations

import base64
import logging
import os
import sys

import httpx
from google import genai

from app.models.image import ImageGenerationRequest, ImageGenerationResponse
from app.services.providers.base import decode_optional_image
from app.utils.prompts import EDIT_PROMPT, GENERATE_PROMPT

log = logging.getLogger(__name__)

QUOTA_HINT = (
    "Google image quota is exhausted for this API key "
    "(free tier limit is 0 for Nano Banana on this project). "
    "Enable billing in Google AI Studio, or switch IMAGE_PROVIDER "
    "to a free edit API such as deAPI."
)


class GeminiQuotaError(RuntimeError):
    """Raised when Gemini returns RESOURCE_EXHAUSTED / free-tier limit 0."""


def _gemini_client() -> genai.Client:
    # Windows installs often fail Google TLS with missing system CAs.
    insecure = os.environ.get("DRAWDASH_INSECURE_SSL", "").strip().lower() in {
        "1",
        "true",
        "yes",
    }
    if not insecure and sys.platform == "win32":
        insecure = True
        log.warning(
            "Using unverified httpx client for Gemini on Windows "
            "(set DRAWDASH_INSECURE_SSL=false to force cert checks)"
        )
    if insecure:
        return genai.Client(
            http_options={
                "httpx_client": httpx.Client(verify=False, timeout=180.0),
            }
        )
    return genai.Client()


def _raise_gemini_failure(exc: Exception) -> None:
    message = str(exc)
    lowered = message.lower()
    if (
        "429" in message
        or "resource_exhausted" in lowered
        or "quota exceeded" in lowered
        or "limit: 0" in lowered
    ):
        raise GeminiQuotaError(QUOTA_HINT) from exc
    raise RuntimeError(f"Failed to generate image: {exc}") from exc


class GeminiImageProvider:
    def __init__(self) -> None:
        self.client = _gemini_client()
        self.model = "gemini-2.5-flash-image"

    async def generate(
        self, request: ImageGenerationRequest
    ) -> ImageGenerationResponse:
        log.info("Using IMAGE_PROVIDER=gemini-image (Nano Banana)")
        prompt_template = GENERATE_PROMPT if request.type == "generate" else EDIT_PROMPT
        prompt = prompt_template.format(user_prompt=request.prompt)

        contents: list = [prompt]
        reference = decode_optional_image(request.image_data)
        if reference is not None:
            contents.append(reference)

        try:
            response = self.client.models.generate_content(
                model=self.model, contents=contents
            )
        except Exception as e:
            log.error("Error calling Gemini image API: %s", e)
            _raise_gemini_failure(e)

        if not response.candidates:
            raise ValueError("No response generated by the model")

        generated_image_data = None
        text_response = None
        for part in response.candidates[0].content.parts:
            if part.text is not None:
                text_response = part.text
            elif part.inline_data is not None:
                generated_image_data = base64.b64encode(part.inline_data.data).decode(
                    "utf-8"
                )

        if not generated_image_data:
            raise ValueError("No image generated by the model")

        return ImageGenerationResponse(
            image_data=generated_image_data, text_response=text_response
        )
