"""Free Gemini Flash text → SVG → PNG provider."""

from __future__ import annotations

import logging

from google import genai

from app.models.image import ImageGenerationRequest, ImageGenerationResponse
from app.services.providers.base import (
    decode_optional_image,
    extract_svg,
    image_to_base64_png,
    rasterize_svg,
)
from app.utils.prompts import SVG_EDIT_PROMPT, SVG_GENERATE_PROMPT

log = logging.getLogger(__name__)


class SvgLlmProvider:
    def __init__(self) -> None:
        self.client = genai.Client()
        self.model = "gemini-2.5-flash"

    async def generate(
        self, request: ImageGenerationRequest
    ) -> ImageGenerationResponse:
        log.info("Using IMAGE_PROVIDER=svg-llm (free Flash → SVG → PNG)")
        prompt_template = (
            SVG_GENERATE_PROMPT if request.type == "generate" else SVG_EDIT_PROMPT
        )
        prompt = prompt_template.format(user_prompt=request.prompt)

        contents: list = [prompt]
        reference = decode_optional_image(request.image_data)
        if reference is not None:
            contents.append(reference)

        try:
            response = self.client.models.generate_content(
                model=self.model, contents=contents
            )
        except Exception as e:
            log.error("Error calling Gemini Flash API: %s", e)
            raise RuntimeError(f"Failed to generate SVG diagram: {e}") from e

        if not response.candidates:
            raise ValueError("No response generated by the model")

        text_response = None
        for part in response.candidates[0].content.parts:
            if part.text is not None:
                text_response = (text_response or "") + part.text

        if not text_response:
            raise ValueError("Model returned no text/SVG")

        svg = extract_svg(text_response)
        image = rasterize_svg(svg)
        return ImageGenerationResponse(
            image_data=image_to_base64_png(image),
            text_response=text_response[:500],
        )
